module Fhir
 autoload :Quantity, 'fhir/types/quantity.rb'
 autoload :Address, 'fhir/types/address.rb'
 autoload :Choice, 'fhir/types/choice.rb'
 autoload :Contact, 'fhir/types/contact.rb'
 autoload :Extension, 'fhir/types/extension.rb'
 autoload :Coding, 'fhir/types/coding.rb'
 autoload :HumanName, 'fhir/types/human_name.rb'
 autoload :Schedule, 'fhir/types/schedule.rb'
 autoload :Quantity, 'fhir/types/quantity.rb'
 autoload :Attachment, 'fhir/types/attachment.rb'
 autoload :Quantity, 'fhir/types/quantity.rb'
 autoload :Quantity, 'fhir/types/quantity.rb'
 autoload :SampledData, 'fhir/types/sampled_data.rb'
 autoload :Quantity, 'fhir/types/quantity.rb'
 autoload :Range, 'fhir/types/range.rb'
 autoload :Quantity, 'fhir/types/quantity.rb'
 autoload :Period, 'fhir/types/period.rb'
 autoload :Identifier, 'fhir/types/identifier.rb'
 autoload :Narrative, 'fhir/types/narrative.rb'
 autoload :ResourceReference, 'fhir/types/resource_reference.rb'
 autoload :Ratio, 'fhir/types/ratio.rb'
 autoload :CodeableConcept, 'fhir/types/codeable_concept.rb'
end
